<a href="https://colab.research.google.com/github/vohoangtien290905/Thuc-Hanh-DeepLearning/blob/main/Lab_1/Lab1_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0
zero_tensor = tf.zeros([2, 3])

# Hiển thị tensor
print(zero_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [2]:
X = tf.constant([[1, 2, 3], [4, 5, 6]])

zero_like_X_tensor = tf.zeros_like(X)

print("Tensor X:")
print(X)
print("\nTensor zero_like_X_tensor:")
print(zero_like_X_tensor)

Tensor X:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Tensor zero_like_X_tensor:
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


In [3]:
# Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5
five_tensor = tf.fill([3, 2], 5)

# Hiển thị tensor
print(five_tensor)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


In [4]:
# Xác định các số chẵn trong khoảng [5, 10]
even_numbers_in_range = tf.constant([6, 8, 10])

# Tính toán số lần lặp lại cần thiết để có ít nhất 50 phần tử
num_repetitions = tf.cast(tf.math.ceil(50 / tf.cast(tf.size(even_numbers_in_range), dtype=tf.float32)), dtype=tf.int32)

# Lặp lại tensor và cắt để có chính xác 50 phần tử
tensor_50_even = tf.tile(even_numbers_in_range, [num_repetitions])[:50]

print("Tensor 1-chiều với 50 phần tử chẵn:")
print(tensor_50_even)
print("Kích thước tensor:", tensor_50_even.shape)

Tensor 1-chiều với 50 phần tử chẵn:
tf.Tensor(
[ 6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10
  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10  6  8 10
  6  8], shape=(50,), dtype=int32)
Kích thước tensor: (50,)


In [5]:
# Tạo một tensor có kích thước [3, 2] với giá trị ngẫu nhiên theo phân phối normal
# mean=0, standard deviation = 2
random_normal_tensor = tf.random.normal(shape=[3, 2], mean=0.0, stddev=2.0)

# Hiển thị tensor
print(random_normal_tensor)

tf.Tensor(
[[ 1.0956857  -0.43055356]
 [-0.13611898  1.9673002 ]
 [-1.8860819   0.52995324]], shape=(3, 2), dtype=float32)


In [6]:
X = tf.constant([[1, 2], [3, 4], [5, 6]])

shuffled_X = tf.random.shuffle(X)

print("Tensor X ban đầu:")
print(X)
print("\nTensor X sau khi xáo trộn:")
print(shuffled_X)

Tensor X ban đầu:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)

Tensor X sau khi xáo trộn:
tf.Tensor(
[[3 4]
 [1 2]
 [5 6]], shape=(3, 2), dtype=int32)


In [7]:
# Định nghĩa hai tensor x và y
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])

# Tính tổng của hai tensor
sum_tensor = tf.add(x, y) # Hoặc đơn giản là x + y

# Hiển thị kết quả
print("Tensor x:", x)
print("Tensor y:", y)
print("Tổng của x và y:", sum_tensor)

Tensor x: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor y: tf.Tensor([4 5 6], shape=(3,), dtype=int32)
Tổng của x và y: tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [8]:
# Tạo một tensor ngẫu nhiên kích thước (10, 10, 3)
original_tensor = tf.random.uniform(shape=(10, 10, 3), minval=0, maxval=255, dtype=tf.int32)

# Cắt ngẫu nhiên tensor thành kích thước (5, 5, 3)
cropped_tensor = tf.image.random_crop(original_tensor, size=[5, 5, 3])

print("Tensor gốc (kích thước", original_tensor.shape, "):")
print(original_tensor)
print("\nTensor đã cắt (kích thước", cropped_tensor.shape, "):")
print(cropped_tensor)

Tensor gốc (kích thước (10, 10, 3) ):
tf.Tensor(
[[[134 180  63]
  [ 96 239  54]
  [ 86 206 152]
  [114 232 230]
  [ 70 103 154]
  [124 162  20]
  [154 134 127]
  [ 11 205  85]
  [ 76 214 252]
  [121  52 129]]

 [[ 15 103  51]
  [ 84 177 201]
  [ 19 217 125]
  [201 135 105]
  [194  20 174]
  [ 50 201 222]
  [167 194 201]
  [  1  27 102]
  [ 74 126 168]
  [222 175 164]]

 [[114 118 103]
  [225  55 112]
  [ 46 158  38]
  [165 101 222]
  [220  33 129]
  [ 29  82  83]
  [ 52  89 183]
  [179 251  82]
  [ 95 183 116]
  [236  48 117]]

 [[220  80 115]
  [198  50 233]
  [ 62 170 236]
  [202 201  18]
  [173  23  26]
  [ 24  14 127]
  [178 253   5]
  [ 56  23 253]
  [203 210  71]
  [251 112  46]]

 [[211 126 142]
  [190 121  38]
  [226 104 173]
  [118 144  55]
  [168 114   4]
  [201   4  55]
  [249 243 114]
  [192  54 248]
  [172  30 136]
  [120 198 207]]

 [[ 67 199 175]
  [ 54 183  54]
  [ 51 230   9]
  [135 130  51]
  [ 38 221  80]
  [ 33 166  85]
  [ 66 128  85]
  [189 135  19]
  [135 236  2